language: java

# check out the dependency
before_install:
  - cd ${TRAVIS_BUILD_DIR}/..
  - git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-actors.git
  - cd vlingo-actors && mvn install -DskipTests=true
  - cd ${TRAVIS_BUILD_DIR} # back to the origin

script:
  - mvn install
